// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ5Oxh7tQcHtcJhW_LDC1bm8sPhPM5AcA',
    appId: '1:1061161360246:web:258dd0c9809a39bca5f857',
    messagingSenderId: '1061161360246',
    projectId: 'andriod-meeting-app',
    authDomain: 'andriod-meeting-app.firebaseapp.com',
    storageBucket: 'andriod-meeting-app.firebasestorage.app',
    measurementId: 'G-FPNLQMNEQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlHv-Of_2d_3ooMcSpLHXnfoorWLeGSuA',
    appId: '1:1061161360246:android:a26ede99c01addc9a5f857',
    messagingSenderId: '1061161360246',
    projectId: 'andriod-meeting-app',
    storageBucket: 'andriod-meeting-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWuC4hwl66QTLQNGBJn1x1NujutWQnYKQ',
    appId: '1:1061161360246:ios:73ed09d061540f1ca5f857',
    messagingSenderId: '1061161360246',
    projectId: 'andriod-meeting-app',
    storageBucket: 'andriod-meeting-app.firebasestorage.app',
    iosBundleId: 'com.example.audioMeetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWuC4hwl66QTLQNGBJn1x1NujutWQnYKQ',
    appId: '1:1061161360246:ios:73ed09d061540f1ca5f857',
    messagingSenderId: '1061161360246',
    projectId: 'andriod-meeting-app',
    storageBucket: 'andriod-meeting-app.firebasestorage.app',
    iosBundleId: 'com.example.audioMeetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ5Oxh7tQcHtcJhW_LDC1bm8sPhPM5AcA',
    appId: '1:1061161360246:web:2fbc9b07e533c117a5f857',
    messagingSenderId: '1061161360246',
    projectId: 'andriod-meeting-app',
    authDomain: 'andriod-meeting-app.firebaseapp.com',
    storageBucket: 'andriod-meeting-app.firebasestorage.app',
    measurementId: 'G-ZGBTB613TM',
  );
}
